FROM python:3.11

RUN apt-get update -y

RUN apt install libgl1-mesa-glx -y

RUN apt-get install 'ffmpeg'\
    'libsm6'\
    'libxext6' \
    'poppler-utils' \
    'tesseract-ocr' \
    'tesseract-ocr-eng' -y

CMD ["python3"]